In [7]:
import pandas as pd
import numpy as np

In [8]:
df=pd.read_csv("Automobile_data[1].csv")

In [10]:
df.head(3)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0

1. what is the average price and average mileage for convertible cars

In [12]:
df.groupby(["body-style"])[["price","average-mileage"]].agg(["mean"])

                    price average-mileage
                     mean            mean
body-style
convertible  22341.000000       19.666667
hardtop      39714.000000       15.500000
hatchback     7159.571429       30.466667
sedan        17706.333333       24.937500
wagon        12730.111111       25.444444

In [13]:
convertible_cars=df[df["body-style"]=="convertible"]
convertible_cars

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
46,62,porsche,convertible,89.5,168.9,ohcf,six,207,17,37028.0

In [54]:
price= convertible_cars["price"].mean()
print(f"Average price for convertible cars : {price}")

Average price for convertible cars : 22341.0

In [55]:
mileage=convertible_cars["average-mileage"].mean()
print(f"Average mileage for convertible cars : {mileage}")

Average mileage for convertible cars : 19.666666666666668

2. Sort cars by company and price in decending order

In [57]:
decen_ordr=df.sort_values(by=["company", "price"], ascending=[False, False])
print(f"Cars sorted by company and price : \n{decen_ordr}")

Cars sorted by company and price :
    index      company   body-style  wheel-base  length engine-type  \
60     88        volvo        wagon       104.3   188.8         ohc
59     87        volvo        sedan       104.3   188.8         ohc
58     86   volkswagen        sedan        97.3   171.7         ohc
57     82   volkswagen        sedan        97.3   171.7         ohc
56     81   volkswagen        sedan        97.3   171.7         ohc
..    ...          ...          ...         ...     ...         ...
5       5         audi        sedan        99.8   177.3         ohc
3       3         audi        sedan        99.8   176.6         ohc
1       1  alfa-romero  convertible        88.6   168.8        dohc
2       2  alfa-romero    hatchback        94.5   171.2        ohcv
0       0  alfa-romero  convertible        88.6   168.8        dohc

   num-of-cylinders  horsepower  average-mileage    price  decision
60             four         114               23  13415.0       buy
59             four         114               23  12940.0       buy
58             four         100               26   9995.0  dont buy
57             four          52               37   7995.0  dont buy
56             four          85               27   7975.0  dont buy
..              ...         ...              ...      ...       ...
5              five         110               19  15250.0       buy
3              four         102               24  13950.0       buy
1              four         111               21  16500.0  dont buy
2               six         154               19  16500.0  dont buy
0              four         111               21  13495.0  dont buy

[61 rows x 11 columns]

3. Save data for 'Toyota' separately

In [67]:
Toyota=df[df["company"]=="toyota"]
Toyota

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
48,66,toyota,hatchback,95.7,158.7,ohc,four,62,35,5348.0
49,67,toyota,hatchback,95.7,158.7,ohc,four,62,31,6338.0
50,68,toyota,hatchback,95.7,158.7,ohc,four,62,31,6488.0
51,69,toyota,wagon,95.7,169.7,ohc,four,62,31,6918.0
52,70,toyota,wagon,95.7,169.7,ohc,four,62,27,7898.0
53,71,toyota,wagon,95.7,169.7,ohc,four,62,27,8778.0
54,79,toyota,wagon,104.5,187.8,dohc,six,156,19,15750.0

4. which company is producing most expensive car?

In [60]:
mx=df.groupby(["company"])["price"].max()
print(f"Company producing most expensive car:\n{mx}")

Company producing most expensive car:
company
alfa-romero      16500.0
audi             18920.0
bmw              41315.0
chevrolet         6575.0
dodge             6377.0
honda            12945.0
isuzu             6785.0
jaguar           36000.0
mazda            18344.0
mercedes-benz    45400.0
mitsubishi        8189.0
nissan           13499.0
porsche          37028.0
toyota           15750.0
volkswagen        9995.0
volvo            13415.0
Name: price, dtype: float64

In [63]:
mx = df.groupby("company")["price"].max()
print(f"Company producing most expensive car:{mx.idxmax()}")

Company producing most expensive car:mercedes-benz

5. Name the cars on basis of maximum length, highest wheelbase, maximum horsepower

In [66]:
length=df.nlargest(1,"length")[["company"]]
print(f"Cars on the basis of maximum length :\n {length}")

Cars on the basis of maximum length :
           company
34  mercedes-benz

In [70]:
wheel_base=df.nlargest(1,"wheel-base")[["company"]]
print(f"Cars on the basis of maximum wheel base :\n {wheel_base}")

Cars on the basis of maximum wheel base :
           company
34  mercedes-benz

In [71]:
horsepower=df.nlargest(1,"horsepower")[["company"]]
print(f"Cars on the basis of maximum horsepower :\n {horsepower}")

Cars on the basis of maximum horsepower :
     company
47  porsche

In [46]:
df.groupby(["company"])[["length","wheel-base","horsepower"]].max()

               length  wheel-base  horsepower
company
alfa-romero     171.2        94.5         154
audi            192.7       105.8         115
bmw             197.0       110.0         182
chevrolet       158.8        94.5          70
dodge           157.3        93.7          68
honda           175.4        96.5         101
isuzu           170.7        94.5          78
jaguar          199.6       113.0         262
mazda           175.0       104.9         101
mercedes-benz   208.1       120.9         184
mitsubishi      172.4        96.3          88
nissan          184.6       100.4         152
porsche         175.7        98.4         288
toyota          187.8       104.5         156
volkswagen      171.7        97.3         100
volvo           188.8       104.3         114

6. company wise average price of cars and order them in decending order

In [84]:
df.groupby(["company"])[["price"]].mean().sort_values(by="price", ascending=False)

                      price
company
porsche        35528.000000
mercedes-benz  35040.000000
jaguar         34600.000000
bmw            27213.333333
audi           16392.500000
alfa-romero    15498.333333
volvo          13177.500000
honda          10195.000000
mazda           9654.800000
volkswagen      8435.000000
nissan          8289.000000
toyota          8216.857143
isuzu           6785.000000
mitsubishi      6689.000000
dodge           6303.000000
chevrolet       6007.000000

7. create a column named: "decision", If wheel-base is less than 100 and length is less than 175 then "don't buy" else "buy

In [24]:
df["decision"] = np.where((df["wheel-base"] < 100) & (df["length"] < 175),"dont buy","buy")

In [30]:
df.head(2)

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,decision
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0,dont buy
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0,dont buy

8. Select only cars whose decision is "buy"; find average price based on company of car

In [44]:
df[df["decision"]=="buy"].groupby("company")["price"].mean()

company
audi             16392.500000
bmw              27213.333333
honda            12945.000000
jaguar           34600.000000
mazda            18344.000000
mercedes-benz    35040.000000
nissan           13499.000000
porsche                   NaN
toyota           15750.000000
volvo            13177.500000
Name: price, dtype: float64